/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData find_doctor__1_ =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData qrcode = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData emergency = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData covid__2_ = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData qrscan__1_ = IconData(0xe805, fontFamily: _kFontFam);
}
